---
# ============================================================
# INSTALL RKE2 MASTER
# ============================================================
- name: Install RKE2 Master
  hosts: MASTER
  become: true

  tasks:

    - name: Download and install RKE2 server
      shell: curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=server sh -
      args:
        warn: false

    - name: Enable and start RKE2 server
      systemd:
        name: rke2-server
        enabled: true
        state: started

    - name: Wait for token file to be created
      wait_for:
        path: /var/lib/rancher/rke2/server/token
        timeout: 120

    - name: Read RKE2 master token
      slurp:
        src: /var/lib/rancher/rke2/server/token
      register: token_file

    - name: Save token to host facts
      set_fact:
        rke2_token: "{{ token_file.content | b64decode | trim }}"

    - name: Show extracted token (debug)
      debug:
        msg: "RKE2 token is {{ rke2_token }}"


# ============================================================
# INSTALL RKE2 WORKER
# ============================================================
- name: Install RKE2 Worker
  hosts: WORKER
  become: true

  vars:
    master_ip: "{{ hostvars[groups['MASTER'][0]]['ansible_host'] | default(groups['MASTER'][0]) }}"
    rke2_token: "{{ hostvars[groups['MASTER'][0]]['rke2_token'] }}"

  tasks:

    - name: Download and install RKE2 agent
      shell: curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=agent sh -
      args:
        warn: false

    - name: Create RKE2 config directory
      file:
        path: /etc/rancher/rke2
        state: directory
        mode: '0755'

    - name: Create worker config.yaml
      copy:
        dest: /etc/rancher/rke2/config.yaml
        content: |
          server: https://{{ master_ip }}:9345
          token: {{ rke2_token }}
      mode: '0644'

    - name: Enable and start RKE2 agent
      systemd:
        name: rke2-agent
        enabled: true
        state: restarted
