---
# ---------------------------------------------------------
# INSTALL RKE2 MASTER
# ---------------------------------------------------------
- name: Install RKE2 Master
  hosts: MASTER
  become: true

  tasks:

    - name: Install RKE2 server
      shell: curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=server sh -

    - name: Enable + start RKE2 server
      systemd:
        name: rke2-server
        enabled: yes
        state: started

    - name: Wait for RKE2 token file
      wait_for:
        path: /var/lib/rancher/rke2/server/token
        timeout: 120

    - name: Read token file
      slurp:
        src: /var/lib/rancher/rke2/server/token
      register: token_raw

    - name: Decode token
      set_fact:
        rke2_token: "{{ token_raw.content | b64decode | trim }}"

    - name: Show token (debug)
      debug:
        msg: "Master token is {{ rke2_token }}"


# ---------------------------------------------------------
# INSTALL RKE2 WORKER
# ---------------------------------------------------------
- name: Install RKE2 Worker
  hosts: WORKER
  become: true

  vars:
    master_ip: "{{ hostvars[groups['MASTER'][0]].ansible_host }}"

  tasks:

    - name: Install RKE2 agent
      shell: curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=agent sh -

    - name: Create RKE2 config directory
      file:
        path: /etc/rancher/rke2
        state: directory
        mode: '0755'

    - name: Create worker config.yaml
      copy:
        dest: /etc/rancher/rke2/config.yaml
        mode: '0644'
        content: |
          server: https://{{ master_ip }}:9345
          token: {{ hostvars[groups['MASTER'][0]].rke2_token }}

    - name: Enable and start RKE2 agent
      systemd:
        name: rke2-agent
        enabled: yes
        state: started
